export enum ActionCardType {
  ROCK_FALL,
  MAP,
  DESTROY_PICKAXE,
  DESTROY_CART,
  DESTROY_LAMP,
  REPAIR_PICKAXE,
  REPAIR_CART,
  REPAIR_LAMP,
  REPAIR_LAMP_OR_CART,
  REPAIR_LAMP_OR_PICKAXE,
  REPAIR_CART_OR_PICKAXE
}
